name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install gh-pages --save-dev
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Install gh-pages dependency"
